---
x-aws-env-variables: &aws-env-variables
  AWS_ACCESS_KEY_ID: aws-access-key-id
  AWS_SECRET_ACCESS_KEY: aws-access-key-id
  AWS_ENDPOINT_URL: http://localhost.localstack.cloud:4566
  AWS_BUCKET_NAME: mycostreams-raw-data


x-code-volumes: &code-volumes
  volumes:
    - ./prince_archiver:/app/prince_archiver
    - ./alembic/:/app/alembic


x-code-and-data-volumes: &code-and-data-volumes
  volumes:
    - ./prince_archiver:/app/prince_archiver
    - ./alembic/:/app/alembic
    - input_data:/data


services:
  prince:
    image: prince-archiver
    command: ["python", "-m", "prince_archiver.entrypoints.mock_prince.main"]
    environment:
      INTERVAL: ${INTERVAL:-30}
      DATA_DIR: /data
    <<: *code-and-data-volumes

  event-ingester:
    <<: *code-and-data-volumes

  state-manager:
    environment:
      <<: *aws-env-variables
      RABBITMQ_DSN: amqp://guest:guest@rabbitmq:5672
      SURF_USERNAME: ""
      SURF_PASSWORD: ""
    <<: *code-volumes
    depends_on:
      s3:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  upload-worker:
    environment:
      <<: *aws-env-variables
    <<: *code-and-data-volumes
    depends_on:
      s3:
        condition: service_healthy

  api:
    environment:
      <<: *aws-env-variables
    <<: *code-volumes

  prestart:
    <<: *code-volumes

  s3:
    image: localstack/localstack:latest
    hostname: localhost.localstack.cloud
    ports:
      - 127.0.0.1:4566:4566
    environment:
      SERVICES: "s3"
    volumes:
      - "./scripts/init-localstack.sh:/etc/localstack/init/ready.d/init-localstack.sh"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 5s
      timeout: 5s
      retries: 3

  rabbitmq:
    image: rabbitmq:3.13-management
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 5s
      retries: 3


volumes:
  input_data:
