services:
  data-migration:
    image: mycostreams/prince-archiver:${TAG:-latest}
    command: "./run-data-migrations.sh"
    environment: 
      POSTGRES_DSN: postgresql+asyncpg://postgres:postgres@db:5432/postgres
    depends_on:
      db:
        condition: service_healthy
    volumes:
    - ./scripts/run-data-migrations.sh:/app/run-data-migrations.sh
    - ./prince_archiver:/app/prince_archiver
    - ./alembic/:/app/alembic
    profiles:
      - tools
