---
x-aws-env-variables: &aws-env-variables
  AWS_ACCESS_KEY_ID: aws-access-key-id
  AWS_SECRET_ACCESS_KEY: aws-access-key-id
  AWS_ENDPOINT_URL: http://s3:9090
  AWS_BUCKET_NAME: mycostreams


services:
  prince:
    image: prince-archiver
    command: ["python", "-m", "prince_archiver.entrypoints.mock_prince"]
    environment:
      INTERVAL: ${INTERVAL:-30}
      DATA_DIR: /data/input
    volumes:
      - ./prince_archiver:/app/prince_archiver
      - ./alembic/:/app/alembic
      - input_data:/data/input

  data-ingester:
    volumes:
      - ./prince_archiver:/app/prince_archiver
      - ./alembic:/app/alembic
      - input_data:/data/input

  worker:
    environment:
      <<: *aws-env-variables
      RABBITMQ_DSN: amqp://guest:guest@rabbitmq:5672
      SURF_USERNAME: ""
      SURF_PASSWORD: ""
    volumes:
      - ./prince_archiver:/app/prince_archiver
      - ./alembic/:/app/alembic
    depends_on:
      s3:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  upload-worker:
    environment:
      <<: *aws-env-variables
    volumes:
      - ./prince_archiver:/app/prince_archiver
      - ./alembic/:/app/alembic
      - input_data:/data/input
    depends_on:
      s3:
        condition: service_healthy

  api:
    environment:
      <<: *aws-env-variables
    volumes:
      - ./prince_archiver:/app/prince_archiver
      - ./alembic/:/app/alembic

  db-migrations:
    volumes:
      - ./prince_archiver:/app/prince_archiver
      - ./alembic/:/app/alembic

  s3:
    image: adobe/s3mock:3.10.0
    ports:
      - 9090:9090
      - 9191:9191
    environment:
      initialBuckets: mycostreams
      validKmsKeys: arn:aws:kms:eu-central-1:1234567890:key/aws-access-key-id
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:9090"]
      interval: 5s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3.13-management
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 5s
      retries: 3


volumes:
  input_data:
