---
x-aws-env-variables: &aws-env-variables
  AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
  AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
  AWS_ENDPOINT_URL: https://objectstore.surf.nl
  AWS_REGION_NAME: default
  AWS_BUCKET_NAME: "mycostreams-raw-data"


x-log-labels: &log-labels
  logging: loki
  logging_jobname: ${DEPLOYMENT_NAME-:morricone}


services:
  event-ingester:
    environment:
      SENTRY_DSN: ${SENTRY_DSN}
    volumes:
      - cifs_mount:/data/prince
    labels: *log-labels
    deploy:
      restart_policy:
        condition: on-failure

  state-manager:
    environment:
      ARCHIVE_TRANSITION_DAYS: ${ARCHIVE_TRANSITION_DAYS:-2}
      RABBITMQ_DSN: ${RABBITMQ_DSN}
      SENTRY_DSN: ${SENTRY_DSN}
      SURF_USERNAME: ${SURF_USERNAME}
      SURF_PASSWORD: ${SURF_PASSWORD}
      WEBHOOK_URL: ${WEBHOOK_URL}
    labels: *log-labels
    deploy:
      restart_policy:
        condition: on-failure

  upload-worker:
    environment:
      <<: *aws-env-variables
      SENTRY_DSN: ${SENTRY_DSN}
    volumes:
      - cifs_mount:/data/system/prince:ro
    labels: *log-labels
    deploy:
      restart_policy:
        condition: on-failure

  api:
    environment:
      <<: *aws-env-variables
      SENTRY_DSN: ${SENTRY_DSN}

  aws-cli:
    image: amazon/aws-cli
    environment:
      <<: *aws-env-variables
      AWS_DEFAULT_REGION: default
    volumes:
      - ${POSTGRES_BACKUP_DIR:-${PWD}/backups}:/aws/postgres
      - redis_data:/aws/redis
    profiles:
      - tools

volumes:
  cifs_mount: 
    driver_opts:
      type: cifs
      device: //prince.amolf.nl/Data/Prince2/Images/
      o: username=${AMOLF_USERNAME},password=${AMOLF_PASSWORD}

networks:
  monitoring: 
